### ISSUE TITLE
SpaceVim v0.9.0 TODO list

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#2111]
this is a check list for v0.9.0.

- [ ] release english page
- [ ] release chinese page
- [ ] version
- [ ] milestone https://github.com/SpaceVim/SpaceVim/milestone/12
- [x] support old vim
- [ ] missing lang#puppet layer doc
- [x] missing lang#clojure layer doc
