### ISSUE TITLE
Key bindings TODO

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#3347]
Here, we will list all of the key bindings todos, including adding missing key bindings and remove unused key bindings.
if you need to add other shortcuts, please comment below, any feedback is welcome!

### General key binding

- [x] add `SPC ?` to fuzzy find key binding

### Windows manager

- [x] Remove `Tab` in normal mode. In Vim/Neovim, `Tab` is same as `Ctrl-i` which is a pair key binding of `ctrl-o`, should not be changed in spacevim.
- [x] Change `Shift-Tab` to switch between previous windows and current windows, same as `SPC tab` for buffers.

### file/buffer manager

- [x] #4310
- [x] add copy file url `SPC f Y` (#3348)
- [x] add fuzzy find cursor file in project `SPC p F` (#4309)
- [x] #4311

### Toggles

- [x] #4312

### tab manager

- [x] #4313

### Doc

- [x] doc for `SPC f Y`

**Comment by ilyagr** [comment]
It would  be great is `<Space> ?` worked to give a searchable list of key bindings, like in Spacemacs. It would also be nice if they were linked to a `:help` page.

A little more ambitiously, `<Space> <Space>` could give a searchable list of available Ex commands, ideally with a description and a way to see the documentation.

**Edit:** I see now that the first part of this is implemented if one uses the 'leaderf' layer instead of 'fzf' layer, though it's not quite documented (`<Leader> f SPC` is). It would be nice if the command was present in the `which-key` table and gave a nice error message (instead of "no such command" message) when the wrong layer is used. This command especially if very nice for beginners.

**Comment by wsdjeg** [comment]
@ilyagr Hi, `SPC ?` has been added, did you test it in `leaderf` layer. it should works well.

**Comment by wsdjeg** [comment]
> It would be nice if the command was present in the which-key table and gave a nice error message (instead of "no such command" message) when the wrong layer is used. This command especially if very nice for beginners.

Did you mean, display a suggession instead of `SPC-x-x-x is not difinded!`, for example:

`SPC-x-x-x is defindex in xxxx layer`
