### ISSUE TITLE
Website && Doc && Wiki

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/SpaceVim#3951]
Hello everyone, any feedback about the spacevim website ( [spacevim.org](http://spacevim.org/) ) is welcome. please just leave your comments below, and if your ides is included into this todo list, I will hidden your comments, and make this issue easy to read.

- [x] #4433
- [x] doc for how to reinstall plugins is missing (#4212)
- [ ] how to disable startify, the welcome page. (#4211)
- [x] #4434
- [x] #4435
- [x] #4436
- [x] add info about How do I configure Vim using the Vim script (quick start guide) (#4213)

New contents:

- [ ] Vim script guide: https://github.com/SpaceVim/SpaceVim/pull/3810
- [ ] genral usage for vim/neovim https://github.com/SpaceVim/SpaceVim/pull/3636
- [x] #4437

Bugs need to be fixed:

- [x] ~~relativenumber autocmd break relativenumber option~~

**Comment by chrisRidgers** [comment]
Would it be good to break the documentation page into sub pages.

Think the one view is a bit much - especially given the lack of spacing between sections.

**Comment by chrisRidgers** [comment]
What about a 'generate a valid config'? select your layers hit button, downloads to toml file.  Could have similar buttons on the 'Using SpaceVim as a xxx IDE' pages, for a quick start experience.

**Comment by chrisRidgers** [comment]
What is 'dark powered mode'?

```
The very first time SpaceVim starts up, it will ask you to choose a mode, basic mode or dark powered mode. then it will create a SpaceVim.d/init.toml in your HOME directory. All the configuration files can be stored in ~/.SpaceVim.d/ directory.
```

I selected it at some point, but I don't think I've seen a description of what that gives me vs what basic mode does.

**Comment by chrisRidgers** [comment]
Font configuration

Getting this working in the terminal with the various powerline / symbols was very much trial and error on Manjaro/Linux.

Is it worth fleshing out font install instructions to lead people in the right direction for their OS?  Feels bad to have stumble on that one.

**Comment by chrisRidgers** [comment]
FileTree

Using Vimfiler as the default - Isn't vimfiler now deprecated? Should the docs remove the line about vimfiler being the default and SpaceVims new default be set to defx?

![image](https://user-images.githubusercontent.com/5954265/98880208-254a3980-247f-11eb-8a0a-4717f8403c6a.png)

https://github.com/Shougo/vimfiler.vim

**Comment by chrisRidgers** [comment]
Mappings guide:

What is:

```
[WIN] | windows_leader / s | window mapping prefix of SpaceVim
```

Is that supposed to be the Windows Key (mod key on linux?)

If so I don't think it ever makes it to Vim, at least in my setup.

Maybe this section could be fleshed out with better descriptions and recommendations for alternative leader bindings?

**Comment by chrisRidgers** [comment]
ahhhh

found this in a different section:

![image](https://user-images.githubusercontent.com/5954265/98880637-14e68e80-2480-11eb-92fe-24f7a4bda3b9.png)


Maybe that should be repeated in the mappings guide?  Or at least linked to in the mappings guide?

**Comment by wsdjeg** [comment]
Thanks!



> Would it be good to break the documentation page into sub pages.
> 
> Think the one view is a bit much - especially given the lack of spacing between sections.

yeah, but current jekyll theme do not support subpage, it will be hard to native between pages.



> What about a 'generate a valid config'? select your layers hit button, downloads to toml file. Could have similar buttons on the 'Using SpaceVim as a xxx IDE' pages, for a quick start experience.

maybe we can add example in `use vim as xxx ide` page.



> What is 'dark powered mode'?
> 
> ```
> The very first time SpaceVim starts up, it will ask you to choose a mode, basic mode or dark powered mode. then it will create a SpaceVim.d/init.toml in your HOME directory. All the configuration files can be stored in ~/.SpaceVim.d/ directory.
> ```
> 
> I selected it at some point, but I don't think I've seen a description of what that gives me vs what basic mode does.

you can check the `mode/` directory in spacevim repo.

> Font configuration
> 
> Getting this working in the terminal with the various powerline / symbols was very much trial and error on Manjaro/Linux.
> 
> Is it worth fleshing out font install instructions to lead people in the right direction for their OS? Feels bad to have stumble on that one.

this should be included in fonts configuration section. :+1:




> Mappings guide:
> 
> What is:
> 
> ```
> [WIN] | windows_leader / s | window mapping prefix of SpaceVim
> ```
> 
> Is that supposed to be the Windows Key (mod key on linux?)
> 
> If so I don't think it ever makes it to Vim, at least in my setup.
> 
> Maybe this section could be fleshed out with better descriptions and recommendations for alternative leader bindings?

yeah, this should be updated.

**Comment by MuhammedZakir** [comment]
This one is empty -- https://spacevim.org/faq/#where-is-my-old-vim-configuration.

**Comment by Diablo-D3** [comment]
It is not currently documented how to easily disable startify, as this might be a sticking point for easy adoption.

**Comment by pyrox0** [comment]
I can start a project to fix all the grammar errors on the site, if you want me to.

**Comment by wsdjeg** [comment]
@ModdedGamers that would be nice, thank you.

**Comment by pyrox0** [comment]
Alright, I will get started on this ASAP. How often should I submit PRs?

**Comment by Diablo-D3** [comment]
It is not currently documented that `[options] relativenumber = false` exists and works.

**Comment by pyrox0** [comment]
That's because it's a built-in vim feature. Also, I have stopped working on my fork due to IRL complications.

**Comment by Diablo-D3** [comment]
As far as I know, Spacevim uses behavior similar to...
```
autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu | set rnu   | endif
autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu | set nornu | endif
```
... which isn't built in. Merely doing `set nornu` in `bootstrap#after` doesn't permanently remove it since the `autocmd` puts it back... which is why `relativenumber` exists as an option. It merely is not documented. This is the documentation improvement bug ;)

**Comment by wsdjeg** [comment]
> As far as I know, Spacevim uses behavior similar to...
> 
> ```
> autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu | set rnu   | endif
> autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu | set nornu | endif
> ```
> 
> ... which isn't built in. Merely doing `set nornu` in `bootstrap#after` doesn't permanently remove it since the `autocmd` puts it back... which is why `relativenumber` exists as an option. It merely is not documented. This is the documentation improvement bug ;)

I think this is a bug of SpaceVim, this autocmd should be disabled.

**Comment by wsdjeg** [comment]
@Diablo-D3 in spacevim if `g:spacevim_relativenumber` is false, this autocmd will not be added, please read:

```
    if g:spacevim_relativenumber
      autocmd BufEnter,WinEnter * if &nu | set rnu   | endif
      autocmd BufLeave,WinLeave * if &nu | set nornu | endif
    endif
```

**Comment by Diablo-D3** [comment]
Yes, and that should be documented. It seems to be a question asked frequently in the various support areas.

**Comment by 0xIsho** [comment]
@ModdedGamers Have you started the project? I would like to help out :)

**Comment by pyrox0** [comment]
I did, but I abandoned it because I am too busy these days to work on this. Sorry, but you are free to work on it yourself!

**Comment by 0xIsho** [comment]
Alright then, I'll push a branch on my fork to work on it.

Also @wsdjeg should i open a single pull request for the whole thing, or break it into multiple pull requests?

**Comment by wsdjeg** [comment]
@IshoAntar thanks, you can use a single PR.

**Comment by smbkr** [comment]
The first time Spacevim is run, it asks the user to choose between "basic mode" and "dark powered mode", with no explanation offered as to what these modes are. The documentation on the website also doesn't have any explanation on what this means.

**Comment by wsdjeg** [comment]
@smbkr yeah, we should add more description about what thses mode are.

**Comment by wsdjeg** [comment]
I will closed this issue, because all checkbox has been changed to issue.

**Comment by Doomwhite** [comment]
The follow mode isn't really explained anywhere;
There's a typo on the fuzzy finder section(Discription);
On the Undo tree 'key bindings' and 'description' aren't capitalized correctly.

**Comment by wsdjeg** [comment]
Use new issue please, all checkbox has been moved to issue.
